/**
 * src/tests/features/flags/is-enabled.test.ts
 * Generated by AI session on 2026-09-05T13:30:00+07:00 (Run 5, Condition A).
 */
import { beforeEach, describe, expect, it } from "vitest";
import { isEnabled } from "@/features/flags/lib/is-enabled";

describe("isEnabled", () => {
  beforeEach(() => {
    delete process.env.FLAG_DARK_MODE_DEFAULT;
    delete process.env.FLAG_BILLING_V2;
  });

  it("returns fallback when no override is set", () => {
    expect(isEnabled("dark_mode_default", false)).toBe(false);
    expect(isEnabled("billing_v2", true)).toBe(true);
  });

  it("respects env var override FLAG_<KEY>", () => {
    process.env.FLAG_BILLING_V2 = "true";
    expect(isEnabled("billing_v2", false)).toBe(true);
  });

  it("caches result within 5 minutes", () => {
    process.env.FLAG_DARK_MODE_DEFAULT = "true";
    const a = isEnabled("dark_mode_default", false);
    process.env.FLAG_DARK_MODE_DEFAULT = "false";
    const b = isEnabled("dark_mode_default", false);
    expect(a).toBe(b);
    expect(a).toBe(true);
  });
});
