/**
 * features/flags/lib/is-enabled.ts
 *
 * Run 7 — Condition A. Generated by an AI session on 2026-09-06 under
 * the §4 prompt. Async variant — the per-user DB layer is async,
 * matching the rest of SmartKit's data-access patterns. Cache stays
 * 5-minute per (flag, userId) and process-local.
 */
import "server-only";

import {
  FlagKeySchema,
  type FlagKey,
  getFlagKeys,
  isValidFlagKey,
} from "../types/flags";

const FIVE_MINUTES_IN_MS = 5 * 60 * 1000;

interface CachedValue {
  result: boolean;
  expiresAtMs: number;
}

const cache = new Map<string, CachedValue>();

function buildCacheKey(flagKey: FlagKey, userId: string | undefined): string {
  return userId ? `${flagKey}::${userId}` : `${flagKey}::_anon_`;
}

async function loadUserOverride(
  userId: string | undefined,
  _flagKey: FlagKey,
): Promise<boolean | null> {
  if (!userId) return null;
  // No per-user flag table is wired in this pilot. The DB layer would
  // resolve here. Returning null signals "fall through to env / default".
  return null;
}

function loadEnvOverride(flagKey: FlagKey): boolean | null {
  const envVarName = `FLAG_${flagKey.toUpperCase()}`;
  const raw = process.env[envVarName];
  if (raw === undefined) return null;
  if (raw === "true") return true;
  if (raw === "false") return false;
  return null;
}

/**
 * Resolve a feature flag with the documented three-layer override:
 *   1. Per-user DB override (only when `userId` is passed)
 *   2. Per-flag env var `FLAG_<KEY>=true|false`
 *   3. `fallback` default value
 *
 * Results are cached in-memory for 5 minutes, keyed by `<flag>:<userId|'_anon_'>`.
 * The function is `async` to accommodate the per-user DB lookup.
 */
export async function isEnabled(
  flagKey: string,
  fallback: boolean,
  userId?: string,
): Promise<boolean> {
  if (!isValidFlagKey(flagKey)) {
    throw new Error(
      `Unknown flag "${flagKey}". Allowed: ${getFlagKeys().join(", ")}`,
    );
  }
  const key = buildCacheKey(flagKey, userId);
  const now = Date.now();
  const cached = cache.get(key);
  if (cached !== undefined && cached.expiresAtMs > now) {
    return cached.result;
  }

  const userOverride = await loadUserOverride(userId, flagKey);
  if (userOverride !== null) {
    cache.set(key, { result: userOverride, expiresAtMs: now + FIVE_MINUTES_IN_MS });
    return userOverride;
  }

  const envOverride = loadEnvOverride(flagKey);
  if (envOverride !== null) {
    cache.set(key, { result: envOverride, expiresAtMs: now + FIVE_MINUTES_IN_MS });
    return envOverride;
  }

  cache.set(key, { result: fallback, expiresAtMs: now + FIVE_MINUTES_IN_MS });
  return fallback;
}

export { FlagKeySchema, type FlagKey };
