/**
 * features/flags/lib/is-enabled.ts
 * Generated by AI session on 2026-09-05T13:26:00+07:00 (Run 4, Condition A).
 *
 * Server-side flag check utility. Per FSD convention:
 *   - colocated in features/flags/lib/ (per SmartKit AGENTS.md)
 *   - server-only boundary import
 *   - Zod-typed FlagKey (imported from ./types/flags)
 *   - 5-minute in-memory cache
 */
import "server-only";

import { type FlagKey, FlagKeySchema, isFlagKey } from "../types/flags";

const TTL_MS = 5 * 60 * 1000;
const cache = new Map<string, { value: boolean; expiresAt: number }>();

function buildCacheKey(flag: FlagKey, userId?: string): string {
  return userId ? `${flag}::${userId}` : `${flag}::_`;
}

function readUserOverride(userId: string | undefined, flag: FlagKey): boolean | undefined {
  if (!userId) return undefined;
  // SmartKit has no per-user DB override wired for the pilot feature.
  // Stubbed to keep the resolution path observable.
  return undefined;
}

export function isEnabled(flag: FlagKey, defaultValue: boolean, userId?: string): boolean {
  if (!isFlagKey(flag)) {
    throw new Error(`Invalid flag key: ${String(flag)}`);
  }
  const cacheKey = buildCacheKey(flag, userId);
  const now = Date.now();
  const cached = cache.get(cacheKey);
  if (cached && cached.expiresAt > now) {
    return cached.value;
  }

  const userOverride = readUserOverride(userId, flag);
  if (userOverride !== undefined) {
    cache.set(cacheKey, { value: userOverride, expiresAt: now + TTL_MS });
    return userOverride;
  }

  const envName = `FLAG_${flag.toUpperCase()}`;
  const envRaw = process.env[envName];
  if (envRaw !== undefined) {
    const value = envRaw === "true";
    cache.set(cacheKey, { value, expiresAt: now + TTL_MS });
    return value;
  }

  cache.set(cacheKey, { value: defaultValue, expiresAt: now + TTL_MS });
  return defaultValue;
}

// Re-export schema so consumers don't need to know the file split.
export { FlagKeySchema };
export type { FlagKey };
