/**
 * features/flags/types/flags.ts
 *
 * Run 8 — Condition A. Generated by an AI session on 2026-09-06 under
 * the §4 prompt. SCREAMING_SNAKE_CASE flag keys, 5 entries chosen by the
 * AI to demonstrate business-relevant toggles.
 */
import { z } from "zod";

const FLAG_KEY_TUPLE = [
  "STRIPE_V2",
  "APPLE_PAY",
  "INVITE_ONLY",
  "STAGING_MODE",
  "MULTI_TENANT",
] as const;

export const FlagKeySchema = z.enum(FLAG_KEY_TUPLE);

export type FlagKey = z.infer<typeof FlagKeySchema>;
