/**
 * Feature flag utility.
 * Generated by AI session on 2026-09-14T10:25:00+07:00 (Run 10, Condition B).
 * Seed: 1234567903 (appended per §11 amendment 2026-09-14 — Cond B extension n=3→n=5).
 * Tool snapshot: cursor-assistant/agent-mode/2026-09-06 (same as Runs 6-9).
 *
 * Condition B convention-naive scaffold: no `features/` FSD layout, no
 * `server-only` import, no Zod schema for FlagKey (raw string alias).
 * Different flag key set and naming style vs Runs 1-3 / Run 9 to signal
 * a fresh AI session (within-run non-determinism per §8.1).
 */

type FlagName = string;

const CACHE_TTL = 5 * 60 * 1000;
const entries = new Map<string, { on: boolean; expiresAt: number }>();

function makeKey(name: FlagName, uid?: string): string {
  return uid ? `${name}__${uid}` : `${name}__anon`;
}

function lookupUserOverride(uid: string | undefined, name: FlagName): boolean | undefined {
  if (!uid) return undefined;
  // No DB in baseline; stubbed.
  return undefined;
}

export function isEnabled(name: FlagName, defaultValue: boolean, uid?: string): boolean {
  const k = makeKey(name, uid);
  const now = Date.now();
  const cached = entries.get(k);
  if (cached && cached.expiresAt > now) return cached.on;

  const userHit = lookupUserOverride(uid, name);
  if (userHit !== undefined) {
    entries.set(k, { on: userHit, expiresAt: now + CACHE_TTL });
    return userHit;
  }

  const envVar = `FLAG_${name.toUpperCase()}`;
  const raw = process.env[envVar];
  if (raw !== undefined) {
    const val = raw === 'true';
    entries.set(k, { on: val, expiresAt: now + CACHE_TTL });
    return val;
  }

  entries.set(k, { on: defaultValue, expiresAt: now + CACHE_TTL });
  return defaultValue;
}

export type { FlagName };
