/**
 * features/flags/types/flags.ts
 *
 * Run 6 — Condition A. Generated by an AI session on 2026-09-06 under
 * the §4 prompt. FlagKey is derived from a Zod enum so TypeScript's
 * inference picks up the literal union (per SmartKit conventions:
 * Zod-first types, never raw string aliases).
 */
import { z } from "zod";

export const FlagKeySchema = z.enum([
  "DARK_MODE",
  "BETA_FEATURES",
  "ANALYTICS",
  "NEW_DASHBOARD",
]);

export type FlagKey = z.infer<typeof FlagKeySchema>;

export const ALL_FLAG_KEYS = FlagKeySchema.options;

export function isFlagKey(value: unknown): value is FlagKey {
  return FlagKeySchema.safeParse(value).success;
}
