/**
 * features/flags/types/flags.ts
 * Generated by AI session on 2026-09-05T13:30:00+07:00 (Run 5, Condition A).
 */
import { z } from "zod";

export const FlagKeySchema = z.enum([
  "experimental_search",
  "oauth_provider_google",
  "new_dashboard_layout",
  "billing_v2",
  "dark_mode_default",
]);

export type FlagKey = z.infer<typeof FlagKeySchema>;

export const FLAG_KEYS = FlagKeySchema.options;
