/**
 * features/flags/lib/is-enabled.ts
 *
 * Run 8 — Condition A. Generated by an AI session on 2026-09-06 under
 * the §4 prompt. Sync variant, dual-Map cache (separate value and
 * expiration stores), server-only boundary, 5-minute TTL.
 */
import "server-only";

import { FlagKeySchema, type FlagKey } from "../types/flags";

const TTL_MS = 5 * 60 * 1000;

// Two parallel maps — values holds the resolved boolean, expirations
// holds the wall-clock timestamp at which the entry expires. The pair
// is logically a record; splitting them keeps individual map operations
// straightforward.
const values = new Map<string, boolean>();
const expirations = new Map<string, number>();

const buildCacheKey = (flag: FlagKey, userId?: string): string =>
  userId ? `${flag}__${userId}` : `${flag}___`;

const readUserOverride = (
  _userId: string | undefined,
  _flag: FlagKey,
): boolean | undefined => {
  // Per-user DB override is not wired in this pilot. The DB layer would
  // resolve here and return true/false; returning undefined signals
  // "no override, fall through to env / default".
  return undefined;
};

const readEnvOverride = (flag: FlagKey): boolean | undefined => {
  const raw = process.env[`FLAG_${flag}`];
  if (raw === "true") return true;
  if (raw === "false") return false;
  return undefined;
};

/**
 * Resolve a feature flag with the documented three-layer override:
 *   1. Per-user DB override (only when `userId` is passed)
 *   2. Per-flag env var `FLAG_<KEY>=true|false`
 *   3. `fallback` default value (defaults to `false`)
 *
 * Results are cached in-memory for 5 minutes, keyed by
 * `<flag>:<userId|'_'>`.
 */
export function isEnabled(
  flag: unknown,
  fallback: boolean = false,
  userId?: string,
): boolean {
  const parsed = FlagKeySchema.safeParse(flag);
  if (!parsed.success) {
    throw new Error(
      `Invalid flag key: ${JSON.stringify(flag)}. ` +
        `Allowed: ${FlagKeySchema.options.join(", ")}`,
    );
  }
  const key = buildCacheKey(parsed.data, userId);
  const now = Date.now();

  const expires = expirations.get(key);
  if (expires !== undefined && expires > now) {
    const cached = values.get(key);
    if (cached !== undefined) return cached;
  }

  let resolved: boolean | undefined = readUserOverride(userId, parsed.data);
  if (resolved === undefined) {
    resolved = readEnvOverride(parsed.data);
  }
  if (resolved === undefined) {
    resolved = fallback;
  }

  values.set(key, resolved);
  expirations.set(key, now + TTL_MS);
  return resolved;
}

export { FlagKeySchema, type FlagKey };
