/**
 * features/flags/lib/is-enabled.ts
 *
 * Run 6 — Condition A. Generated by an AI session on 2026-09-06 under
 * the §4 prompt. Per SmartKit conventions:
 *   - FSD placement under features/flags/lib/
 *   - server-only boundary import (no browser bundling)
 *   - Zod-derived FlagKey enum
 *   - 5-minute in-memory cache, process-local
 *   - barrel re-export in features/flags/index.ts
 */
import "server-only";

import {
  ALL_FLAG_KEYS,
  type FlagKey,
  FlagKeySchema,
  isFlagKey,
} from "../types/flags";

// 5 minutes per Prompt B §4.
const CACHE_TTL_MS = 5 * 60 * 1000;

interface CacheEntry {
  value: boolean;
  expiresAt: number;
}

const cache = new Map<string, CacheEntry>();

function makeCacheKey(flag: FlagKey, userId: string | undefined): string {
  return userId ? `${flag}#${userId}` : `${flag}#__`;
}

function readUserOverride(
  userId: string | undefined,
  _flag: FlagKey,
): boolean | undefined {
  if (!userId) return undefined;
  // No per-user flag table is wired in this pilot. The DB layer would
  // resolve here; fall through to env/default.
  return undefined;
}

function readEnvOverride(flag: FlagKey): boolean | undefined {
  const raw = process.env[`FLAG_${flag}`];
  if (raw === "true") return true;
  if (raw === "false") return false;
  return undefined;
}

/**
 * Resolve `flag` to a boolean using the documented three-layer override:
 *   1. Per-user DB override (only when `userId` is passed)
 *   2. Per-flag env var `FLAG_<KEY>`
 *   3. `fallback` default value (defaults to `false`)
 *
 * Result is cached in-memory for 5 minutes keyed by `<flag>:<userId|'_'>`.
 */
export function isEnabled(
  flag: unknown,
  fallback: boolean = false,
  userId?: string,
): boolean {
  if (!isFlagKey(flag)) {
    throw new Error(
      `Invalid flag key: ${JSON.stringify(flag)}. Allowed: ${ALL_FLAG_KEYS.join(", ")}`,
    );
  }
  const key = makeCacheKey(flag, userId);
  const now = Date.now();
  const cached = cache.get(key);
  if (cached && cached.expiresAt > now) {
    return cached.value;
  }

  const userOverride = readUserOverride(userId, flag);
  if (userOverride !== undefined) {
    cache.set(key, { value: userOverride, expiresAt: now + CACHE_TTL_MS });
    return userOverride;
  }

  const envOverride = readEnvOverride(flag);
  if (envOverride !== undefined) {
    cache.set(key, { value: envOverride, expiresAt: now + CACHE_TTL_MS });
    return envOverride;
  }

  cache.set(key, { value: fallback, expiresAt: now + CACHE_TTL_MS });
  return fallback;
}

export { FlagKeySchema, type FlagKey };
