/**
 * features/flags/types/flags.ts
 *
 * Run 7 — Condition A. Generated by an AI session on 2026-09-06 under
 * the §4 prompt. A `getFlagKeys()` helper is exposed alongside the
 * Zod-derived enum to support reflection (e.g., admin debug panels).
 */
import { z } from "zod";

export const FlagKeySchema = z.enum([
  "new_pricing",
  "sepay_checkout",
  "ai_assistant_v1",
  "audit_log",
  "graphql_endpoint",
]);

export type FlagKey = z.infer<typeof FlagKeySchema>;

export function getFlagKeys(): readonly FlagKey[] {
  return FlagKeySchema.options;
}

export function isValidFlagKey(value: unknown): value is FlagKey {
  return typeof value === "string" && FlagKeySchema.safeParse(value).success;
}
