/* Server-only shim for tsx runtime.
 *
 * The real `server-only` package (shipped by Next.js) is a virtual module
 * that throws when imported outside a Next.js server bundler. tsx scripts
 * run with bare Node, so we substitute a no-op shim before any
 * `import 'server-only'` is evaluated.
 *
 * This shim is regenerated by ensure-server-only-shim.ts on every
 * pretest run, so a `pnpm install` cannot wipe it out.
 */
export {};
