/**
 * Feature flags.
 * Generated by AI session on 2026-09-05T13:22:00+07:00 (Run 3, Condition B).
 */

const FLAG_PREFIX = "FLAG_";
const CACHE_DURATION = 5 * 60 * 1000;

const cache = new Map<string, { enabled: boolean; ts: number }>();

function key(flag: string, userId?: string): string {
  return userId ? `${flag}|${userId}` : `${flag}|anon`;
}

function userOverride(uid: string | undefined): boolean | null {
  return null;
}

export function isEnabled(flag: string, defaultValue: boolean, userId?: string): boolean {
  const k = key(flag, userId);
  const now = Date.now();
  const hit = cache.get(k);
  if (hit && now - hit.ts < CACHE_DURATION) return hit.enabled;

  const ovr = userOverride(userId);
  if (ovr !== null) {
    cache.set(k, { enabled: ovr, ts: now });
    return ovr;
  }

  const envKey = FLAG_PREFIX + flag.toUpperCase();
  const env = process.env[envKey];
  if (env !== undefined) {
    const v = env === "true";
    cache.set(k, { enabled: v, ts: now });
    return v;
  }

  cache.set(k, { enabled: defaultValue, ts: now });
  return defaultValue;
}
