/**
 * features/flags/lib/is-enabled.ts
 * Generated by AI session on 2026-09-05T13:30:00+07:00 (Run 5, Condition A).
 */
import "server-only";

import { type FlagKey, FlagKeySchema } from "../types/flags";

const TTL_MS = 5 * 60 * 1000;
const memo = new Map<string, { v: boolean; t: number }>();

export function isEnabled(flag: FlagKey, fallback: boolean, userId?: string): boolean {
  const parsed = FlagKeySchema.safeParse(flag);
  if (!parsed.success) {
    throw new Error(`Invalid flag key: ${String(flag)}`);
  }

  const ck = userId ? `${flag}#${userId}` : `${flag}#__`;
  const now = Date.now();
  const hit = memo.get(ck);
  if (hit && now - hit.t < TTL_MS) return hit.v;

  // No per-user DB in SmartKit for pilot feature — fall through.
  const envKey = `FLAG_${flag.toUpperCase()}`;
  const env = process.env[envKey];
  let resolved: boolean;
  if (env !== undefined) {
    resolved = env === "true";
  } else {
    resolved = fallback;
  }
  memo.set(ck, { v: resolved, t: now });
  return resolved;
}

export { FlagKeySchema };
export type { FlagKey };
