/**
 * Feature flag check utility.
 * Generated by AI session on 2026-09-14T10:20:00+07:00 (Run 9, Condition B).
 * Seed: 1234567902 (appended per §11 amendment 2026-09-14 — Cond B extension n=3→n=5).
 * Tool snapshot: cursor-assistant/agent-mode/2026-09-06 (same as Runs 6-8).
 *
 * Public API: isEnabled(flagKey, defaultValue, userId?)
 * Resolution order: per-user override > env var > default value
 *
 * Condition B convention-naive scaffold: no `features/` FSD layout, no
 * `server-only` import, no Zod schema for FlagKey (raw string alias).
 */

type FlagKey = string;

const TTL_MS = 5 * 60 * 1000;
const memo = new Map<string, { v: boolean; e: number }>();

function cacheKey(flag: FlagKey, uid?: string): string {
  return uid ? `${flag}@${uid}` : `${flag}@_`;
}

function dbOverride(uid: string | undefined, flag: FlagKey): boolean | null {
  if (!uid) return null;
  // No DB wired in baseline; stub returns null so resolution falls through.
  return null;
}

export function isEnabled(flag: FlagKey, fallback: boolean, uid?: string): boolean {
  const k = cacheKey(flag, uid);
  const now = Date.now();
  const hit = memo.get(k);
  if (hit && hit.e > now) return hit.v;

  const userVal = dbOverride(uid, flag);
  if (userVal !== null) {
    memo.set(k, { v: userVal, e: now + TTL_MS });
    return userVal;
  }

  const envKey = `FLAG_${flag.toUpperCase().replace(/-/g, '_')}`;
  const envRaw = process.env[envKey];
  if (envRaw !== undefined) {
    const parsed = envRaw === 'true';
    memo.set(k, { v: parsed, e: now + TTL_MS });
    return parsed;
  }

  memo.set(k, { v: fallback, e: now + TTL_MS });
  return fallback;
}

export type { FlagKey };
