/**
 * Feature flag utility.
 * Generated by AI session on 2026-09-05T13:18:00+07:00 (Run 2, Condition B).
 */

type FeatureFlag = string;

const TTL = 5 * 60 * 1000;
const store = new Map<string, { val: boolean; exp: number }>();

function buildKey(flag: FeatureFlag, uid?: string): string {
  return `${flag}::${uid ?? "_"}`;
}

function readUserOverride(uid: string | undefined, flag: FeatureFlag): boolean | null {
  if (!uid) return null;
  // No DB in baseline; stubbed.
  return null;
}

export function isEnabled(flag: FeatureFlag, fallback: boolean, uid?: string): boolean {
  const k = buildKey(flag, uid);
  const now = Date.now();
  const hit = store.get(k);
  if (hit && hit.exp > now) return hit.val;

  const userVal = readUserOverride(uid, flag);
  if (userVal !== null) {
    store.set(k, { val: userVal, exp: now + TTL });
    return userVal;
  }

  const envName = `FLAG_${flag.toUpperCase()}`;
  const envVal = process.env[envName];
  if (envVal !== undefined) {
    const parsed = envVal === "true" || envVal === "1";
    store.set(k, { val: parsed, exp: now + TTL });
    return parsed;
  }

  store.set(k, { val: fallback, exp: now + TTL });
  return fallback;
}

export type { FeatureFlag };
