/**
 * features/flags/types/flags.ts
 * Generated by AI session on 2026-09-05T13:26:00+07:00 (Run 4, Condition A).
 *
 * FlagKey enum derived from Zod schema (c2-direction §5.3 Type & Contract Safety).
 */
import { z } from "zod";

export const FlagKeySchema = z.enum([
  "new_billing_flow",
  "dark_mode",
  "beta_features",
  "show_pricing_v2",
  "enable_oauth_google",
]);

export type FlagKey = z.infer<typeof FlagKeySchema>;

export const FLAG_KEYS = FlagKeySchema.options;

export const isFlagKey = (value: unknown): value is FlagKey =>
  FlagKeySchema.safeParse(value).success;
