/**
 * Feature flag check utility.
 * Generated by AI session on 2026-09-05T13:14:00+07:00 (Run 1, Condition B).
 *
 * Public API: isEnabled(flagKey, defaultValue, userId?)
 * Resolution order: per-user override > env var > default value
 */

type FlagKey = string;

const cache = new Map<string, { value: boolean; expires: number }>();
const CACHE_TTL_MS = 5 * 60 * 1000;

function getCacheKey(flagKey: FlagKey, userId?: string): string {
  return userId ? `${flagKey}:${userId}` : `${flagKey}:`;
}

function getUserOverride(userId: string | undefined, flagKey: FlagKey): boolean | undefined {
  if (!userId) return undefined;
  // Convention-naive baseline has no DB connection wired up; this stub
  // returns undefined so resolution falls through to env/default.
  return undefined;
}

export function isEnabled(flagKey: FlagKey, defaultValue: boolean, userId?: string): boolean {
  const cacheKey = getCacheKey(flagKey, userId);
  const now = Date.now();
  const cached = cache.get(cacheKey);
  if (cached && cached.expires > now) {
    return cached.value;
  }

  const userOverride = getUserOverride(userId, flagKey);
  if (userOverride !== undefined) {
    cache.set(cacheKey, { value: userOverride, expires: now + CACHE_TTL_MS });
    return userOverride;
  }

  const envName = `FLAG_${flagKey.toUpperCase().replace(/[^A-Z0-9]/g, '_')}`;
  const envRaw = process.env[envName];
  if (envRaw !== undefined) {
    const value = envRaw === 'true';
    cache.set(cacheKey, { value, expires: now + CACHE_TTL_MS });
    return value;
  }

  cache.set(cacheKey, { value: defaultValue, expires: now + CACHE_TTL_MS });
  return defaultValue;
}

export type { FlagKey };
