/**
 * src/tests/features/flags/is-enabled.test.ts
 * Generated by AI session on 2026-09-05T13:26:00+07:00 (Run 4, Condition A).
 *
 * ≥3 cases: env override, default value, cache hit.
 */
import { beforeEach, describe, expect, it } from "vitest";
import { isEnabled } from "@/features/flags/lib/is-enabled";

describe("isEnabled", () => {
  beforeEach(() => {
    delete process.env.FLAG_DARK_MODE;
    delete process.env.FLAG_NEW_BILLING_FLOW;
  });

  it("returns default value when no env var is set", () => {
    expect(isEnabled("dark_mode", false)).toBe(false);
    expect(isEnabled("new_billing_flow", true)).toBe(true);
  });

  it("returns env var override when FLAG_<KEY> is set", () => {
    process.env.FLAG_DARK_MODE = "true";
    expect(isEnabled("dark_mode", false)).toBe(true);
  });

  it("caches result for 5 minutes (cache hit returns stale value)", () => {
    process.env.FLAG_NEW_BILLING_FLOW = "true";
    const first = isEnabled("new_billing_flow", false);
    process.env.FLAG_NEW_BILLING_FLOW = "false";
    const second = isEnabled("new_billing_flow", false);
    expect(first).toBe(second);
    expect(first).toBe(true);
  });

  it("throws on invalid flag key (Zod validation at boundary)", () => {
    // @ts-expect-error: invalid flag key by design
    expect(() => isEnabled("not_a_flag", false)).toThrow();
  });
});
